CREATE TABLE user_followers (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    follower_id TEXT REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL
);
