CREATE TABLE user_followers (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    username TEXT REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL
);
